name: Android Public Build

inputs:
  token:
    required: true
    
runs:
  using: "composite"

  steps:
    - name: Checkout and Set up JDK 17
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        check-latest: true

    - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

    - name: Build debug APK
      run: ./gradlew assembleRelease lintVitalRelease
      shell: bash
    
    - name: Run Local Tests
      run: ./gradlew test
      shell: bash

    - name: Fetch public keystore
      run: wget https://github.com/tytydraco/public-keystore/raw/main/public.jks
      shell: bash

    - name: Sign release APK
      run: |
        apksigner="$(find $ANDROID_SDK_ROOT/build-tools -name apksigner | sort -r | head -n 1)"
        "$apksigner" sign --ks public.jks --ks-key-alias public --ks-pass pass:public --key-pass pass:public --in app/build/outputs/apk/debug/app-debug-unsigned.apk --out app/build/outputs/apk/debug/app-debug.apk
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 10
        compression-level: 9
